// TODO: These don't belong here!

const templates = {
    de: {
        'base::admonition': `Guten Tag,

am {request_date} hatte ich eine Anfrage nach Art. {request_article} DSGVO an Sie gerichtet.[controller_responded> Ich nehme Bezug auf Ihre Antwort darauf vom {response_date}.]
[has:issue_list>
Leider bin ich aus den folgenden Gründen nicht der Meinung, dass Sie meine Anfrage ausreichend entsprechend der Vorgaben der DSGVO beantwortet haben:

{issue_list}
][has:additional_data_list>
Ich reiche die folgenden Informationen nach, wie von Ihnen erbeten:

{additional_data_list}
][has:issue_list>
Ich wende mich daher hiermit erneut an Sie und fordere Sie auf, meine Anfrage innerhalb von zwei Wochen ab Eintreffen dieser Mahnung zufriedenstellend zu beantworten. Andernfalls behalte ich mir vor rechtliche Schritte gegen Sie einzuleiten und Beschwerde bei der zuständigen Datenschutzaufsichtsbehörde einzureichen.
]
Vielen Dank.

Mit freundlichen Grüßen`,
        'base::complaint': `Guten Tag,

hiermit reiche ich Beschwerde nach Art. 77 DSGVO gegen folgende Verantwortliche ein:
{request_recipient_address}

Meine Beschwerde bezieht sich auf eine Anfrage nach Art. {request_article} DSGVO, die ich an die Verantwortliche gerichtet habe. Im Rahmen dieser Anfrage hat die folgende Korrespondenz zwischen der Verantwortlichen und mir stattgefunden:

{correspondence_list}

Die Korrespondenz mit der Verantwortlichen habe ich Ihnen an diese Beschwerde angehängt.

Ich bin der Ansicht, dass die Verantwortliche meine Rechte durch ihre Handhabung meiner Anfrage aus den folgenden Gründen verletzt hat:

{issue_list}

Aufgrund des beschriebenen Sachverhalts gehe ich davon aus, dass die Verantwortliche gegen die DSGVO verstoßen hat. Daher wende ich mich nun mit meiner Beschwerde an Sie und bitte Sie, das beschriebene Verfahren im Rahmen Ihrer Befugnisse gemäß Art. 58 Abs. 1 DSGVO zu prüfen und die Verantwortliche anzuweisen, meiner Anfrage zu entsprechen.

Ich bitte Sie weiterhin, mich nach Art. 77 Abs. 2 DSGVO und Art. 57 Abs. 1 lit. f DSGVO im Laufe des Beschwerdeverfahrens, spätestens aber innerhalb von drei Monaten (vgl. Art. 78 Abs. 2 DSGVO), über dessen Stand und Ergebnisse zu informieren.

[allow_sharing_data_with_controller>Sie dürfen meine Daten zur Bearbeitung der Beschwerde an die Verantwortliche weitergeben.][not:allow_sharing_data_with_controller>Ich bitte Sie, meine Daten <bold>nicht</bold> an die Verantwortliche weitergeben.]

Sollten Sie weitere Informationen von mir benötigen, wenden Sie sich gerne an mich. Sie erreichen mich wie folgt:
{contact_details}
Ich bedanke mich bereits im Voraus für Ihre Unterstützung.

Mit freundlichen Grüßen`,

        'additional-id::admonition': `Sie haben sich geweigert, meine Anfrage zu beantworten, solange ich nicht zusätzliche Identifizierungsdaten zur Verfügung stelle.  Bitte beachten Sie, dass Art. 12 Abs. 6 DSGVO vorschreibt, dass Sie nur dann zusätzliche Informationen anfordern dürfen, wenn Sie begründete Zweifel an meiner Identität haben.[no_doubts> Sie haben keine derartigen Zweifel dargelegt. Es sind auch keine ersichtlich].

Ich bin der Meinung, dass die Daten, die ich in meinem Antrag bereits angegeben habe, ausreichen, um mich zu identifizieren, und dass Sie daher keine weiteren Daten von mir verlangen können.[has:reasoning> {reasoning}][concerns_online_account> Beachten Sie auch, dass Erwägungsgrund 64 DSGVO klarstellt, dass Online-Kennungen zur Identifizierung verwendet werden sollten, insbesondere im Zusammenhang mit Online-Diensten, wie es hier der Fall ist.]`,
        'additional-id::you-said-that::issue': `das Unternehmen sich geweigert hat, Deine Anfrage zu beantworten, solange Du keine zusätzlichen Identifizierungsdaten zur Verfügung stellst.`,
        'additional-id::you-said-that::meta': `[no_doubts>Du hast gesagt, dass das Unternehmen weder begründete Zweifel an Deiner Identität dargelegt hat noch derartige Zweifel ersichtlich sind.] Du hast gesagt, dass die Identifizierungsdaten in Deiner Anfrage aus folgenden Gründen ausreichen: [has:reasoning> „{reasoning}“][concerns_online_account> Deine Anfrage bezieht sich auf einen Online-Account.]`,
        'additional-id::complaint::persists': `Die Verantwortliche hat sich geweigert, meine Anfrage zu beantworten, solange ich nicht zusätzliche Identifizierungsdaten zur Verfügung stelle. Aber nach Art. 12 Abs. 6 DSGVO, darf sie nur zusätzliche Informationen anfordern, wenn sie begründete Zweifel an meiner Identität hat.[no_doubts> Die Verantwortliche hat keine solchen Zweifel dargelegt. Es sind auch keine ersichtlich.]

Ich bin der Ansicht, dass die Daten, die ich bereits in meiner Anfrage angegeben habe, ausreichen, um mich zu identifizieren und die Verantwortliche daher keine zusätzlichen Informationen verlangen kann.[has:reasoning> {reasoning}][concerns_online_account> Meine Anfrage bezieht sich auf einen Online-Account. Erwägungsgrund 64 DSGVO stellt klar, dass Online-Kennungen zur Identifizierung genutzt werden sollen.]`,
        'additional-id::complaint::resolved': `Die Verantwortliche hatte sich ursprünglich geweigert, meine Anfrage zu beantworten, solange ich keine zusätzlichen Identifizierungsdaten zur Verfügung stelle und damit gegen Art. 12 Abs. 6 DSGVO verstoßen. Diese Angelegenheit wurde inzwischen geklärt.`,

        'id-copy::admonition': `Sie haben sich geweigert, meine Anfrage zu beantworten, bis ich eine Ausweiskopie vorlege. Bitte beachten Sie, dass die Bereitstellung einer Ausweiskopie einen erheblichen Eingriff in die Sicherheit meiner personenbezogenen Daten darstellt und daher nur dann angemessen ist, wenn sie unbedingt erforderlich und geeignet ist und im Einklang mit dem nationalen Recht steht (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 73).[user_objects> Ich glaube nicht, dass dies bei meiner Anfrage der Fall ist.]

[not_linked_to_real_life_identity>Meine Anfrage betrifft Daten, die nicht in Bezug zu meiner realen Identität stehen. Es ist daher nicht ersichtlich, wie die Übermittlung einer Ausweiskopie Ihnen bei der Authentifizierung meiner Anfrage helfen würde.][concerns_online_account>Meine Anfrage betrifft einen Online-Account. Damit gibt es bereits ein besseres und weniger invasives Authentifizierungsverfahren (vgl. Erwägungsgrund 64 GDPR). Folglich ist es unverhältnismäßig, eine Ausweiskopie zu verlangen (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 72).][has:reasoning>
{reasoning}][ask_about_redactions>Ich bin bereit, eine geschwärzte Ausweiskopie für diese Anfrage zur Verfügung zu stellen, aber leider haben Sie mir nicht mitgeteilt, welche Informationen zur Bestätigung meiner Identität erforderlich sind. Nach Ansicht des Europäischen Datenschutzausschusses reichen in der Regel das Ausstellungs- oder Ablaufdatum, die ausstellende Behörde und der vollständige Name aus, und alle anderen Informationen sollten geschwärzt werden (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 75). Bitte teilen Sie mir mit, welche Informationen Sie für notwendig erachten, damit ich den Rest schwärzen kann.

Ich möchte Sie außerdem bereits im Voraus darauf hinweisen, dass eine längere Aufbewahrung der Ausweiskopie, als für die Überprüfung meiner Identität für diese Anfrage erforderlich ist, angesichts der Grundsätze der Zweckbindung und Speicherbegrenzung (Art. 5 Abs. 1 lit. b und e DSGVO) einen Verstoß gegen die DSGVO darstellt. Der Europäische Datenschutzausschuss empfiehlt, einen Vermerk zu machen, dass Sie mein Ausweisdokument überprüft haben, und die Kopie dann sofort zu löschen (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 78).][controller_requires_unredacted>Ich bin bereit, eine Ausweiskopie mit den zu meiner Identifizierung für diese Anfrage notwendigen Informationen zur Verfügung zu stellen, aber leider haben Sie mir mitgeteilt, dass Sie nur ungeschwärzte Kopien akzeptieren. Die Forderung nach einer ungeschwärzten Ausweiskopie ist nur unter sehr engen Voraussetzungen rechtmäßig, die meiner Meinung nach in diesem Fall nicht gegeben sind. Nach Ansicht des Europäischen Datenschutzausschusses reichen in der Regel das Ausstellungs- oder Ablaufdatum, die ausstellende Behörde und der vollständige Name aus, und alle anderen Informationen sollten geschwärzt werden (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 75). Bitte teilen Sie mir mit, welche Informationen Sie für notwendig erachten, damit ich den Rest schwärzen kann.

Ich möchte Sie außerdem bereits im Voraus darauf hinweisen, dass eine längere Aufbewahrung der Ausweiskopie, als für die Überprüfung meiner Identität für diese Anfrage erforderlich ist, angesichts der Grundsätze der Zweckbindung und Speicherbegrenzung (Art. 5 Abs. 1 lit. b und e DSGVO) einen Verstoß gegen die DSGVO darstellt. Der Europäische Datenschutzausschuss empfiehlt, einen Vermerk zu machen, dass Sie mein Ausweisdokument überprüft haben, und die Kopie dann sofort zu löschen (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 78).]`,
        'id-copy::you-said-that::issue': `das Unternehmen sich geweigert hat, Deine Anfrage zu beantworten, bis Du eine[controller_requires_unredacted> ungeschwärzte] Ausweiskopie vorlegst.`,
        'id-copy::you-said-that::meta': `[user_objects>Du hast gesagt, dass die Anforderung einer Ausweiskopie meiner Meinung nach aus den folgenden Gründen nicht angemessen ist: ][not_linked_to_real_life_identity>Deine Anfrage betrifft Daten, die nicht in Bezug zu meiner realen Identität stehen.][concerns_online_account>Deine Anfrage bezieht sich auf einen Online-Account.][has:reasoning>„{reasoning}”][controller_requires_unredacted>Du hast gesagt, dass das Unternehmen eine ungeschwärzte Ausweiskopie verlangt hat.]`,
        'id-copy::complaint::persists': `Das Unternehmen hat sich geweigert, meine Anfrage zu beantworten, bis ich eine Ausweiskopie vorlege. Laut dem Europäischen Datenschutzausschuss ist das nur dann angemessen, wenn es unbedingt erforderlich und geeignet ist und im Einklang mit dem nationalen Recht steht (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 73).[user_objects> Ich glaube nicht, dass dies bei meiner Anfrage der Fall ist.]
[not_linked_to_real_life_identity>Meine Anfrage betrifft Daten, die nicht in Bezug zu meiner realen Identität stehen. Es ist daher nicht ersichtlich, wie die Übermittlung einer Ausweiskopie der Verantwortlichen bei der Authentifizierung meiner Anfrage helfen würde.][concerns_online_account>Meine Anfrage betrifft einen Online-Account. Damit gibt es bereits ein besseres und weniger invasives Authentifizierungsverfahren (vgl. Erwägungsgrund 64 GDPR). Folglich ist es unverhältnismäßig, eine Ausweiskopie zu verlangen (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 72).][has:reasoning>
{reasoning}][controller_requires_unredacted>Ich bin bereit, eine Ausweiskopie mit den zu meiner Identifizierung für diese Anfrage notwendigen Informationen zur Verfügung zu stellen, aber leider hat die Verantwortliche mir mitgeteilt, dass sie nur ungeschwärzte Kopien akzeptiert. Aber nach Ansicht des Europäischen Datenschutzausschusses reichen in der Regel das Ausstellungs- oder Ablaufdatum, die ausstellende Behörde und der vollständige Name aus, und alle anderen Informationen sollten geschwärzt werden (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 75).]`,
        'id-copy::complaint::resolved': `[user_objects>Die Verantwortliche hatte sich ursprünglich geweigert, meine Anfrage zu beantworten, sofern ich keine Ausweiskopie vorlege, was laut dem Europäischen Datenschutzausschuss nur dann angemessen ist, wenn es unbedingt erforderlich und geeignet ist und im Einklang mit dem nationalen Recht steht (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 73).][controller_requires_unredacted>Die Verantwortliche hatte sich ursprünglich geweigert, meine Anfrage zu beantworten, sofern ich keine ungeschwärzte Ausweiskopie vorlege. Aber nach Ansicht des Europäischen Datenschutzausschusses reichen in der Regel das Ausstellungs- oder Ablaufdatum, die ausstellende Behörde und der vollständige Name aus, und alle anderen Informationen sollten geschwärzt werden (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 75).] Diese Angelegenheit wurde inzwischen geklärt.`,

        'wrong-medium::admonition': `Sie haben sich geweigert, meine Anfrage zu beantworten [wrong_transport_medium>weil sie nicht per {medium} gesendet wurde.][not_form>solange ich sie nicht über Ihr Webformular sende.][wrong_contact>mit der Begründung, dass sie an die falsche Kontaktperson gesendet wurde.] Bitte beachten Sie, dass die DSGVO Ihnen nicht erlaubt, zusätzliche Formerfordernisse für Anfragen festzusetzen (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 50). [wrong_transport_medium>Dazu gehört auch die Anforderung, Anfragen auf einem bestimmten Weg zu senden (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 52).][not_form>Das bedeutet, dass Sie zwar ein solches Webformular für Anfragen anbieten können, aber dennoch auch Anfragen, die auf anderem Wege übermittelt werden, nachkommen müssen (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 53, 136).][wrong_contact>Sie sind zwar nicht verpflichtet, Anfragen zu beantworten, die an willkürliche, nicht mit der Angelegenheit befasste Personen gerichtet sind, aber Sie können auch nicht nur Anfragen beantworten, die an eine bestimmte Anlaufstelle gerichtet sind (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 55 ff.)][wrong_contact_customer_service> Ich habe meine Anfrage an Ihren regulären Kund_innenservice/Support gerichtet. Es ist angemessen, von Ihnen zu erwarten, dass Sie meine Anfrage intern korrekt weiterleiten.][wrong_contact_privacy> Ich habe meine Anfrage an die Datenschutz-Anlaufstelle geschickt, die Sie in Ihrer Datenschutzerklärung angegeben haben. Dies ist offensichtlich eine angemessene Kontaktstelle für solche Anfragen. Falls erforderlich, sollten Sie sie intern an die richtige Person oder Abteilung weiterleiten.][wrong_contact_dpo> Ich habe meine Anfrage an Ihre_n Datenschutzbeauftragte_n geschickt, wie in Ihrer Datenschutzerklärung angegeben. Unabhängig davon, ob Ihr_ Datenschutzbeauftragte_r mit der Beantwortung von Anfragen betroffener Personen betraut ist, ist dies eine angemessene Anlaufstelle für solche Anfragen. Falls erforderlich, sollten Sie sie intern an die richtige Person oder Abteilung weiterleiten.][has:wrong_contact_reasoning> {wrong_contact_reasoning}]`,
        'wrong-medium::you-said-that::issue': `das Unternehmen sich geweigert hat, Deine Anfrage zu beantworten, weil Du sie an die falsche Anlaufstelle oder auf dem falschen Weg gesendet hast.`,
        'wrong-medium::you-said-that::meta': `Du hast gesagt, dass das Unternehmen sich geweigert hat, Deine Anfrage zu beantworten, weil [wrong_transport_medium>Du sie nicht per {medium} geschickt hast.][not_form>Du sie nicht über sein Webformular versendet hast.][wrong_contact>sie an die falsche Anlaufstelle geschickt hast.] [wrong_contact_customer_service> Du hast gesagt, dass Du Deine Anfrage an den regulären Kund_innenservice/Support geschickt hast.][wrong_contact_privacy> Du hast gesagt, dass Du Deine Anfrage an die Datenschutz-Anlaufstelle geschickt hast.][wrong_contact_dpo> Du hast gesagt, dass Du Deine Anfrage an die_den Datenschutzbeauftragte_n geschickt hast.][has:wrong_contact_reasoning> Du hast gesagt, dass die Anlaufstelle, an die Du Deine Anfrage geschickt hast, aus folgenden Gründen angemessen ist: „{wrong_contact_reasoning}“]`,
        'wrong-medium::complaint::persists': `Die Verantwortliche hat sich geweigert, meine Anfrage zu beantworten, wrong_transport_medium>weil sie nicht per {medium} gesendet wurde.][not_form>solange ich sie nicht über ihr Webformular sende.][wrong_contact>mit der Begründung, dass sie an die falsche Kontaktperson gesendet wurde.] Die DSGVO erlaubt Verantwortlichen nicht, zusätzliche Formerfordernisse für Anfragen festzusetzen (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 50). [wrong_transport_medium>Dazu gehört auch die Anforderung, Anfragen auf einem bestimmten Weg zu senden (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 52).][not_form>Dazu gehört auch die Anforderung, dass Anfragen über ein Webformular gesendet werden (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 53, 136).][wrong_contact>Während ich anerkenne, dass die Verantwortliche nicht verpflichtet ist, Anfragen zu beantworten, die an willkürliche, nicht mit der Angelegenheit befasste Personen gerichtet sind, kann sie auch nicht nur Anfragen beantworten, die an eine bestimmte Anlaufstelle gerichtet sind (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 55 ff.)][wrong_contact_customer_service> Ich habe meine Anfrage an deb regulären Kund_innenservice/Support der Verantwortlichen gerichtet. Es ist angemessen, von zu erwarten, dass sie meine Anfrage intern korrekt weiterleitet.][wrong_contact_privacy> Ich habe meine Anfrage an die Datenschutz-Anlaufstelle geschickt, welche die Verantwortliche in ihrer Datenschutzerklärung angegeben hat. Dies ist offensichtlich eine angemessene Kontaktstelle für solche Anfragen. Falls erforderlich, sollten die Verantwortliche sie intern an die richtige Person oder Abteilung weiterleiten.][wrong_contact_dpo> Ich habe meine Anfrage an die_den Datenschutzbeauftragte_n der Verantwortlichen geschickt, wie in der Datenschutzerklärung angegeben. Unabhängig davon, ob die_der Datenschutzbeauftragte_r mit der Beantwortung von Anfragen betroffener Personen betraut ist, ist dies eine angemessene Anlaufstelle für solche Anfragen. Falls erforderlich, sollten die Verantwortliche sie intern an die richtige Person oder Abteilung weiterleiten.][has:wrong_contact_reasoning> {wrong_contact_reasoning}]`,
        'wrong-medium::complaint::resolved': `Die Verantwortliche hatte sich ursprünglich geweigert, meine Anfrage zu beantworten, wrong_transport_medium>weil sie nicht per {medium} gesendet wurde.][not_form>solange ich sie nicht über ihr Webformular sende.][wrong_contact>mit der Begründung, dass sie an die falsche Kontaktperson gesendet wurde.] Die DSGVO erlaubt Verantwortlichen nicht, zusätzliche Formerfordernisse für Anfragen festzusetzen (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 50). Diese Angelegenheit wurde inzwischen geklärt.`,

        'signature::admonition': `Sie haben sich geweigert, meine Anfrage zu beantworten, solange ich sie nicht unterschreibe. Bitte beachten Sie, dass die DSGVO Ihnen nicht erlaubt, zusätzliche Formerfordernisse für Anfragen festzusetzen (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 50). Eine Unterschrift kann auch nicht zur Authentifizierung oder Identifizierung genutzt werden[not:signature_on_file>, insbesondere, weil Sie nicht einmal eine Unterschriftenprobe von mir haben, mit der Sie meine Unterschrift vergleichen könnten].`,
        'signature::you-said-that::issue': `das Unternehmen sich geweigert hat, Deine Anfrage zu beantworten, solange Du sie nicht unterschreibst.`,
        'signature::you-said-that::meta': `[not:signature_on_file>Du hast gesagt, dass das Unternehmen keine Unterschriftenprobe von Dir vorliegen hat.][signature_on_file>Du hast gesagt, dass Du Unternehmen eventuell eine Unterschriftenprobe von Dir vorliegen hat.]`,
        'signature::complaint::persists': `Die Verantwortliche hat sich geweigert, meine Anfrage zu beantworten, solange ich sie nicht unterschreibe. Die DSGVO erlaubt Verantwortlichen nicht, zusätzliche Formerfordernisse für Anfragen festzusetzen (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 50). Eine Unterschrift kann auch nicht zur Authentifizierung oder Identifizierung genutzt werden[not:signature_on_file>, insbesondere, weil die Verantwortliche nicht einmal eine Unterschriftenprobe von mir hat, mit der sie meine Unterschrift vergleichen könnte].`,
        'signature::complaint::resolved': `Die Verantwortliche hatte sich ursprünglich geweigert, meine Anfrage zu beantworten, solange ich sie nicht unterschreibe. Aber die DSGVO erlaubt Verantwortlichen nicht, zusätzliche Formerfordernisse für Anfragen festzusetzen (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 50) und eine Unterschrift kann auch nicht zur Authentifizierung oder Identifizierung genutzt werden[not:signature_on_file>, insbesondere, weil die Verantwortliche nicht einmal eine Unterschriftenprobe von mir hat, mit der sie meine Unterschrift vergleichen könnte]. Diese Angelegenheit wurde inzwischen geklärt.`,

        'other-language::admonition': `Sie haben meine Anfrage auf {response_language} beantwortet, obwohl ich meine Anfrage auf {request_language} geschrieben habe.[user_does_not_understand_response_language> Ich verstehe Ihre Antwort auf {response_language} nicht.] Nach Art. 12 Abs. 1 DSGVO müssen Sie Mitteilungen „in präziser, transparenter, verständlicher und leicht zugänglicher Form in einer klaren und einfachen Sprache” übermitteln. Nach dem Europäischen Datenschutzausschuss bedeutet das, dass Sie Anfragen in einer Sprache beantworten müssen, die von betroffenen Personen in den entsprechenden Ländern, in denen sie Ihre Dienste anbieten, verstanden wird. (Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 140)
Bitte beantworten Sie meine Anfrage dementsprechend auf {request_language}.`,
        'other-language::you-said-that::issue': `das Unternehmen auf Deine Anfrage in einer anderen Sprache geantwortet hat.`,
        'other-language::you-said-that::meta': `Du hast gesagt, dass das Unternehmen Deine Anfrage, welche Du auf {request_language} gestellt hast, auf {response_language} beantwortet hat. Du hast gesagt, dass Du die Antwort des Unternehmens auf {response_language}[user_does_not_understand_response_language> nicht] verstehst.`,
        'other-language::complaint::persists': `Die Verantwortliche hat meine Anfrage auf {response_language} beantwortet, obwohl ich meine Anfrage auf {request_language} geschrieben habe.[user_does_not_understand_response_language> Ich verstehe die Antwort auf {response_language} nicht.] Nach Art. 12 Abs. 1 DSGVO muss die Verantwortliche Mitteilungen „in präziser, transparenter, verständlicher und leicht zugänglicher Form in einer klaren und einfachen Sprache” übermitteln. Nach dem Europäischen Datenschutzausschuss bedeutet das, dass sie Anfragen in einer Sprache beantworten muss, die von betroffenen Personen in den entsprechenden Ländern, in denen sie Ihre Dienste anbieten, verstanden wird. (Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 140)`,
        'other-language::complaint::resolved': `Die Verantwortliche hatte meine Anfrage ursprünglich auf {response_language} beantwortet, obwohl ich meine Anfrage auf {request_language} geschrieben habe[user_does_not_understand_response_language> und ich habe die Antwort auf {response_language} der Verantwortlichen nicht verstanden]. Diese Angelegenheit wurde inzwischen geklärt.`,

        'excessive::admonition': `[controller_refuses>Sie haben sich geweigert, aufgrund meiner Anfrage tätig zu werden.][controller_wants_to_charge>Sie wollen eine Gebühr für meine Anfrage erheben.] Nach Art. 12 Abs. 5 DSGVO durfen Sie das nur im Falle offenkundig unbegründeter oder exzessiver Anfragen[controller_gave_no_reasoning> und Sie haben den Nachweis für den offenkundig unbegründeten oder exzessiven Charakter der Anfrage zu erbringen. Das haben Sie nicht getan].[controller_wants_to_charge> Alternativ könnten Sie nach Art. 15 Abs. 3 DSGVO eine Gebühr für weitere Kopien meiner Daten, die ich beantragt habe, erheben.]

Ich glaube nicht, dass Sie [controller_refuses>sich weigern können, aufgrund meiner Anfrage tätig zu werden][controller_wants_to_charge>eine Gebühr für meine Anfrage erheben können][controller_gave_no_reasoning> und Sie haben auch keine Gegenargumente vorgebracht]. [first_request>Dies ist die erste Anfrage, die ich jemals an Sie gerichtet habe. Daher ist für mich nicht ersichtlich, inwiefern sie als unbegründet oder exzessiv angesehen werden könnte. Sie können auch niemals eine Gebühr für die erste Kopie erheben, unabhängig davon, ob Sie deren Anfertigung für zu teuer halten (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 22).][additional_copy_no_prior_request>Ich habe Ihnen noch nie eine Anfrage geschickt. Es ist daher nicht ersichtlich, wie ich eine zusätzliche Kopie meiner Daten beantragen könnte. Sie können für die erste Kopie niemals eine Gebühr erheben, unabhängig davon, ob Sie die Kosten für die Erstellung der Kopie für zu hoch halten (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 22).][concerns_different_data>Sie behaupten, ich würde eine zusätzliche Kopie meiner Daten beantragen. Dies würde jedoch nur dann zutreffen, wenn sich diese Anfrage auf dieselben Daten bezöge wie meine vorherige Anfrage. Betrifft die Anfrage stattdessen andere Daten (z. B. andere Datentypen oder einen anderen Zeitraum), müssen Sie sie als neue Anfrage betrachten, und das Recht auf eine kostenlose Kopie gilt erneut (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 28). Ich glaube, dass dies hier der Fall ist.][has:reasoning>{reasoning}]`,
        'excessive::you-said-that::issue': `das Unternehmen [controller_refuses>sich geweigert hat, aufgrund meiner Anfrage tätig zu werden][controller_wants_to_charge>eine Gebühr für Deine Anfrage erheben will].`,
        'excessive::you-said-that::meta': `[controller_gave_no_reasoning>Du hast gesagt, dass das Unternehmen keinen Grund angegeben hat.][first_request>Du hast gesagt, dass dies Deine erste Anfrage an das Unternehmen war.][additional_copy_no_prior_request>Du hast gesagt, dass das Unternehmen behauptet, Du würdest eine weitere Kopie Deiner Daten beantragen, obwohl dies in Wirklichkeit Deine erste Anfrage an das Unternehmen ist.][concerns_different_data>Du hast gesagt, dass das Unternehmen behauptet, Du würdest eine weitere Kopie Deiner Daten beantragen, obwohl Du der Meinung bist, dass sich Deine Anfrage auf andere Daten bezieht.][has:reasoning>Du hast Deine eigene Begründung angegeben: „{reasoning}“]`,
        'excessive::complaint::persists': `[controller_refuses>Die Verantwortliche hat sich geweigert, aufgrund meiner Anfrage tätig zu werden.][controller_wants_to_charge>Die Verantwortliche will eine Gebühr für meine Anfrage erheben.] Nach Art. 12 Abs. 5 DSGVO darf sie das nur im Falle offenkundig unbegründeter oder exzessiver Anfragen[controller_gave_no_reasoning> und sie hat den Nachweis für den offenkundig unbegründeten oder exzessiven Charakter der Anfrage zu erbringen. Das hat sie nicht getan].[controller_wants_to_charge> Alternativ könnte sie nach Art. 15 Abs. 3 DSGVO eine Gebühr für weitere Kopien meiner Daten, die ich beantragt habe, erheben.]

Ich glaube nicht, dass die Verantwortliche [controller_refuses>sich weigern kann, aufgrund meiner Anfrage tätig zu werden][controller_wants_to_charge>eine Gebühr für meine Anfrage erheben kann][controller_gave_no_reasoning> und sie hat auch keine Gegenargumente vorgebracht]. [first_request>Dies ist die erste Anfrage, die ich jemals an die Verantwortliche gerichtet habe. Daher ist für mich nicht ersichtlich, inwiefern sie als unbegründet oder exzessiv angesehen werden könnte. Die Verantwortliche kann auch niemals eine Gebühr für die erste Kopie erheben, unabhängig davon, ob sie deren Anfertigung für zu teuer hält (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 22).][additional_copy_no_prior_request>Ich habe der Verantwortlichen noch nie eine Anfrage geschickt. Es ist daher nicht ersichtlich, wie ich eine zusätzliche Kopie meiner Daten beantragen könnte. Sie kann für die erste Kopie niemals eine Gebühr erheben, unabhängig davon, ob sie die Kosten für die Erstellung der Kopie für zu hoch hält (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 22).][concerns_different_data>Die Verantwortliche behauptet, ich würde eine zusätzliche Kopie meiner Daten beantragen. Dies würde jedoch nur dann zutreffen, wenn sich diese Anfrage auf dieselben Daten bezöge wie meine vorherige Anfrage. Betrifft die Anfrage stattdessen andere Daten (z. B. andere Datentypen oder einen anderen Zeitraum), muss die Verantwortliche sie als neue Anfrage betrachten, und das Recht auf eine kostenlose Kopie gilt erneut (vgl. Europäischer Datenschutzausschuss, „Guidelines 01/2022 on data subject rights - Right of access“, Version 1.0, Rn. 28). Ich glaube, dass dies hier der Fall ist.][has:reasoning>{reasoning}]`,
        'excessive::complaint::resolved': `[controller_refuses>Die Verantwortliche hatte sich ursprünglich geweigert, aufgrund meiner Anfrage tätig zu werden.][controller_wants_to_charge>Die Verantwortliche wollte ursprünglich eine Gebühr für meine Anfrage erheben.] Nach Art. 12 Abs. 5 DSGVO darf sie das nur im Falle offenkundig unbegründeter oder exzessiver Anfragen. [controller_wants_to_charge> Alternativ könnte sie nach Art. 15 Abs. 3 DSGVO eine Gebühr für weitere Kopien meiner Daten, die ich beantragt habe, erheben.] Dies war hier nicht der Fall. Diese Angelegenheit wurde inzwischen geklärt.`,

        'overdue::admonition': `Sie haben meine Anfrage noch nicht beantwortet. Nach Art. 12 Abs. 3 DSGVO haben Sie einen Monat nach Eingang meiner Anfrage Zeit, um diese zu beantworten. Ich habe meine Anfrage am {request_date} abgeschickt, was bedeutet, dass Sie diese Frist überschritten haben. Nach Art. 12 Abs. 3 DSGVO kann die Frist nur dann um weitere zwei Monate verlängert werden, wenn dies erforderlich ist und Sie mich über die Fristverlängerung und deren Gründe informieren. [no_information_about_extension>Das haben Sie nicht getan.][has:reasoning>Der Grund, den Sie für die Verlängerung angegeben haben, ist meiner Meinung nach nicht akzeptabel: {reasoning}][more_than_three_months>
Sie haben jetzt sogar die verlängerte Dreimonatsfrist überschritten.]`,
        'overdue::you-said-that::issue': `das Unternehmen zu lange gebraucht hat, um Deine Anfrage zu beantworten.`,
        'overdue::you-said-that::meta': `Du hast Deine Anfrage am {request_date} gesendet. [no_information_about_extension>Du hast gesagt, dass das Unternehmen Dich nicht darüber informiert hat, warum sie länger als einen Monat zur Beantwortung Deiner Anfrage brauchen.][has:reasoning>Du hast Deine eigene Begründung angegeben, weshalb Du der Meinung bist, dass die Begründung des Unternehmens für die Fristverlängerung nicht akzeptabel ist: „{reasoning}“]`,
        'overdue::complaint::persists': `Die Verantwortliche hat zu lange gebraucht, um meine Anfrage zu beantworten. Nach Art. 12 Abs. 3 DSGVO hat sie einen Monat nach Eingang meiner Anfrage Zeit, um diese zu beantworten. Ich habe meine Anfrage am {request_date} abgeschickt. Nach Art. 12 Abs. 3 DSGVO kann die Frist nur dann um weitere zwei Monate verlängert werden, wenn dies erforderlich ist und die Verantwortliche mich über die Fristverlängerung und deren Gründe informiert. [no_information_about_extension>Das hat die Verantwortliche nicht getan.][has:reasoning>Der Grund, den die Verantwortliche für die Verlängerung angegeben hat, ist meiner Meinung nach nicht akzeptabel: {reasoning}]
Ich habe immer noch keine Antwort auf meine Anfrage erhalten.`,
        'overdue::complaint::resolved': `Die Verantwortliche hat zu lange gebraucht, um meine Anfrage zu beantworten. Nach Art. 12 Abs. 3 DSGVO hat sie einen Monat nach Eingang meiner Anfrage Zeit, um diese zu beantworten. Ich habe meine Anfrage am {request_date} abgeschickt. Nach Art. 12 Abs. 3 DSGVO kann die Frist nur dann um weitere zwei Monate verlängert werden, wenn dies erforderlich ist und die Verantwortliche mich über die Fristverlängerung und deren Gründe informiert. [no_information_about_extension>Das hat die Verantwortliche nicht getan.][has:reasoning>Der Grund, den die Verantwortliche für die Verlängerung angegeben hat, ist meiner Meinung nach nicht akzeptabel: {reasoning}]
Die Verantwortliche hat meine Anfrage mittlerweile beantwortet, aber durch die Fristüberschreitung dennoch gegen die DSGVO verstoßen.`,
    },
    en: {
        'base::admonition': `To Whom It May Concern:

on {request_date} I sent you a request according to Art. {request_article} GDPR.[controller_responded> I refer to your response dated {response_date}.]
[has:issue_list>
Unfortunately, for the following reasons, I do not believe that you have sufficiently responded to my request in accordance with the requirements of the GDPR:

{issue_list}
][has:additional_data_list>
I am providing the following additional information as requested by you:

{additional_data_list}][has:issue_list>
That is why I am contacting you again. I request that you adequately respond to my request within two weeks from the date of receipt of this message. Otherwise, I reserve the right to take legal action against you and to lodge a complaint with the responsible supervisory authority.
]
Thank you.

Yours sincerely,`,
        'base::complaint': `To Whom It May Concern:

I am hereby lodging a complaint according to Art. 77 GDPR against the following controller:
{request_recipient_address}

My complaint concerns a request according to Art. {request_article} GDPR that I sent to the controller. In the context of this request, the following correspondence has taken place between the controller and me:

{correspondence_list}

I have attached the correspondence with the controller to this complaint.

I believe that the controller has violated my rights by its handling of my request for the following reasons:

{issue_list}

Based on the above, I believe that the controller has violated the GDPR. That is why I am lodging this complaint with you. I ask you to check the described procedure within the scope of your powers pursuant to Art. 58(1) GDPR, and to order the controller to comply with my request.

I further request that you inform me about the progress and the outcome of the complaint in accordance with Art. 77(2) GDPR and Art. 57(1)(f) GDPR during the course of the complaint procedure, but no later than within three months (Art. 78(2) GDPR).

[allow_sharing_data_with_controller>You may share my data with the controller for the purpose of processing the complaint.][not:allow_sharing_data_with_controller>I ask you <bold>not</bold> to share my data with the controller.]

If you need any more details, please feel free to contact me. You can reach me as follows:
{contact_details}
Thank you in advance for your assistance.

Yours sincerely,`,

        'additional-id::admonition': `You have refused to answer my request until I provide additional identification data. Please be aware that Art. 12(6) GDPR mandates that you may only request additional information if you have reasonable doubts concerning my identity.[no_doubts> You have not set forth any such doubts. They are not apparent, either.]

I am of the opinion that the data I have already provided in my request is sufficient to identify me and that you can thus not require me to provide any additional data.[has:reasoning> {reasoning}][concerns_online_account> Also note that Recital 64 GDPR explains that online identifiers should be used for identification, in particular in the context of online services, as is the case here.]`,
        'additional-id::you-said-that::issue': `the company refused to answer your request until you provide additional identification data.`,
        'additional-id::you-said-that::meta': `[no_doubts>You said that the company neither set forth any doubts regarding your identity, nor were they apparent.] You said that the data you provided in your request was sufficient for the following reason: [has:reasoning> “{reasoning}”][concerns_online_account> Your request concerns an online account.]`,
        'additional-id::complaint::persists': `The controller has refused to answer my request unless I provide additional identification data. But according to Art. 12(6) GDPR, they can only request additional information if they have reasonable doubts concerning my identity.[no_doubts> The controller has not set forth any such doubts. They are not apparent, either.]

I am of the opinion that the data I have already provided in my request is sufficient to identify me and that the controller can thus not require me to provide any additional data.[has:reasoning> {reasoning}][concerns_online_account> My request concerns an online account. Recital 64 GDPR explains that online identifiers should be used for identification.]`,
        'additional-id::complaint::resolved': `The controller had initially refused to answer my request unless I provide additional identification data, violating Art. 12(6) GDPR. This issue has since been resolved.`,

        'id-copy::admonition': `You have refused to answer my request until I provide a copy of an identity document. Please note that providing a copy of an identity document is an invasive measure that creates a risk for the security of my personal data, and is as such only appropriate if strictly necessary, suitable, and in line with national law (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 73).[user_objects> I do not believe that this is the case for my request.]
[not_linked_to_real_life_identity>My request concerns data that is not linked to my real-life identity. As such, it is not apparent how providing a copy of an identity document would help you in authenticating my request.][concerns_online_account>My request concerns an online account, which means that a better and less intrusive authentication procedure already exists (cf. Recital 64 GDPR). Consequently, it is disproportionate to require a copy of an identity document (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 72).][has:reasoning>
{reasoning}][ask_about_redactions>I am willing to provide a redacted copy of an identity document for this request but unfortunately you have not told me which information is necessary for confirming my identity. According to the European Data Protection Board, generally, the date of issue or expiry date, the issuing authority and the full name are sufficient, and all other information should be redacted (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 75). Please tell me which information you deem necessary so I can redact the rest.

I also want to point out in advance that storing the copy of my identity document longer than is necessary for verifying my identity for this request is an infringement of the GDPR considering the principles of storage and purpose limitation (Art. 5(1)(b) and (e) GDPR). The European Data Protection Board recommends making a note that you have verified my identity document and then immediately deleting the copy (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 78).][controller_requires_unredacted>I am willing to provide a copy of an identity document with the necessary information to identify me for this request but unfortunately you have told me that you only accept unredacted copies. Requiring an unredacted copy on an identify document is only legal in very narrow circumstances which I don’t think are met in this case. According to the European Data Protection Board, generally, the date of issue or expiry date, the issuing authority and the full name are sufficient, and all other information should be redacted (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 75). Please tell me which information you deem necessary so I can redact the rest.

As a precaution, I also want to already point out that storing the copy of my identity document longer than is necessary for verifying my identity for this request is an infringement of the GDPR considering the principles of storage and purpose limitation (Art. 5(1)(b) and (e) GDPR). The European Data Protection Board recommends making a note that you have verified my identity document and then immediately deleting the copy (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 78).]`,
        'id-copy::you-said-that::issue': `the company refused to answer your request until you provide a[controller_requires_unredacted>n unredacted] copy of an identity document.`,
        'id-copy::you-said-that::meta': `[user_objects>You said you don’t believe that asking for an ID copy was appropriate for this request for the following reason: ][not_linked_to_real_life_identity>Your request concerns data that is not linked to your real-life identity.][concerns_online_account>Your request concerns an online account.][has:reasoning>“{reasoning}”][controller_requires_unredacted>You said that the company required you to submit an unredated ID copy for the request.]`,
        'id-copy::complaint::persists': `The controller has refused to answer my request unless I provide a copy of an identity document. According to the European Data Protection Board, this is only appropriate if strictly necessary, suitable, and in line with national law (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 73).[user_objects> I do not believe that this is the case for my request.]
[not_linked_to_real_life_identity>My request concerns data that is not linked to my real-life identity. As such, it is not apparent how providing a copy of an identity document would help the controller in authenticating my request.][concerns_online_account>My request concerns an online account, which means that a better and less intrusive authentication procedure already exists (cf. Recital 64 GDPR). Consequently, it is disproportionate to require a copy of an identity document (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 72).][has:reasoning>
{reasoning}][controller_requires_unredacted>I am willing to provide a copy of an identity document with the necessary information to identify me for this request but unfortunately the controller has told me that they only accept unredacted copies. But according to the European Data Protection Board, generally, the date of issue or expiry date, the issuing authority and the full name are sufficient, and all other information should be redacted (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 75).]`,
        'id-copy::complaint::resolved': `[user_objects>The controller had initially refused to answer my request unless I provide a copy of an identity document, which, according to the European Data Protection Board, is only appropriate if strictly necessary, suitable, and in line with national law (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 73).][controller_requires_unredacted>The controller had initially refused to answer my request unless I provide an unredacted copy of an identity document, but according to the European Data Protection Board, generally, the date of issue or expiry date, the issuing authority and the full name are sufficient, and all other information should be redacted (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 75).] This issue has since been resolved.`,

        'wrong-medium::admonition': `You have refused to answer my request [wrong_transport_medium>because it was not sent via {medium}.][not_form>unless I send it through your web form/self-service tool.][wrong_contact>claiming that it was sent to the wrong contact.] Please be aware that the GDPR doesn’t allow you to impose any additional formal requirements on requests (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 50). [wrong_transport_medium>This includes requiring requests to be sent via a particular transport medium (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 52).][not_form>This means that while you can offer such a self-service tool or web form for requests, you still have to comply with requests sent via other means (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, paras. 53, 136).][wrong_contact>While you are indeed not required to answer requests sent to random contacts not involved in the matter, you cannot only answer requests sent to a particular point of contact, either (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, paras. 55 et seq.).][wrong_contact_customer_service> I sent my request to your regular customer service/support contact. It is reasonable to expect you to correctly forward my request internally.][wrong_contact_privacy> I sent my request to the privacy contact you specified in your privacy policy. This is obviously a reasonable point of contact for such requests. If necessary, you should forward them to the correct person or department internally.][wrong_contact_dpo> I sent my request to your data protection officer, as specified in your privacy policy. Regardless of whether your data protection officer is tasked with responding to data subject requests, this is a reasonable point of contact for such requests. If necessary, you should forward them to the correct person or department internally.][has:wrong_contact_reasoning> {wrong_contact_reasoning}]`,
        'wrong-medium::you-said-that::issue': `the company refused to answer your request because you sent it to the wrong contact or via the wrong medium.`,
        'wrong-medium::you-said-that::meta': `You said that the company refused to answer your request because [wrong_transport_medium>it was not sent via {medium}.][not_form>you didn’t send it through their web form/self-service tool.][wrong_contact>it was sent to the wrong contact.] [wrong_contact_customer_service> You said that you sent your request to their regular customer service/support contact.][wrong_contact_privacy> You said that you sent your request to the privacy contact.][wrong_contact_dpo> You said that you sent your request to the data protection officer.][has:wrong_contact_reasoning> You said that the point of contact you sent your request to was reasonable for the following reason: “{wrong_contact_reasoning}”]`,
        'wrong-medium::complaint::persists': `The controller has refused to answer my request [wrong_transport_medium>because it was not sent via {medium}.][not_form>unless I send it through their web form/self-service tool.][wrong_contact>claiming that it was sent to the wrong contact.] The GDPR doesn’t allow controllers to impose any additional formal requirements on requests (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 50). [wrong_transport_medium>This includes requiring requests to be sent via a particular transport medium (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 52).][not_form>This includes requiring requests to be sent through a particular web form/self-service tool (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, paras. 53, 136).][wrong_contact>While I acknowledge that controllers are not required to answer requests sent to random contacts not involved in the matter, they cannot only answer requests sent to a particular point of contact, either (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, paras. 55 et seq.).][wrong_contact_customer_service> I sent my request to the controller’s regular customer service/support contact. It is reasonable to expect them to correctly forward my request internally.][wrong_contact_privacy> I sent my request to the privacy contact specified in the controller’s privacy policy. This is obviously a reasonable point of contact for such requests. If necessary, they should forward them to the correct person or department internally.][wrong_contact_dpo> I sent my request to the controller’s data protection officer, as specified in their privacy policy. Regardless of whether their data protection officer is tasked with responding to data subject requests, this is a reasonable point of contact for such requests. If necessary, they should forward them to the correct person or department internally.][has:wrong_contact_reasoning> {wrong_contact_reasoning}]`,
        'wrong-medium::complaint::resolved': `The controller had initially refused to answer my request [wrong_transport_medium>because it was not sent via {medium}.][not_form>unless I send it through their web form/self-service tool.][wrong_contact>claiming that it was sent to the wrong contact.] But the GDPR doesn’t allow controllers to impose any additional formal requirements on requests (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 50). This issue has since been resolved.`,

        'signature::admonition': `You have refused to answer my request unless I sign it. Please be aware that the GDPR doesn’t allow you to impose any additional formal requirements on requests (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 50). A signature can also not be used for authentication or identification.[not:signature_on_file> This is especially true since I have never provided you with my signature in the first place, so you have nothing you could even compare my signature against.]`,
        'signature::you-said-that::issue': `the company refused to answer your request unless you sign it.`,
        'signature::you-said-that::meta': `[not:signature_on_file>You said that the company doesn’t have your signature on file.][signature_on_file>You said that the company may have your signature on file.]`,
        'signature::complaint::persists': `The controller has refused to answer my request unless I sign it. The GDPR doesn’t allow controllers to impose any additional formal requirements on requests (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 50). A signature can also not be used for authentication or identification.[not:signature_on_file> This is especially true since I have never provided them with my signature in the first place, so they have nothing they could even compare my signature against.]`,
        'signature::complaint::resolved': `The controller had initially refused to answer my request unless I sign it. But the GDPR doesn’t allow controllers to impose any additional formal requirements on requests (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 50), and a signature can also not be used for authentication or identification[not:signature_on_file>, especially since I have never even provided the controller with a signature that they could compare against]. This issue has since been resolved.`,

        'other-language::admonition': `You have answered my request in {response_language}, even though my request was in {request_language}.[user_does_not_understand_response_language> I cannot understand your response in {response_language}.] According to Art. 12(1) GDPR, you have to provide communication related to requests in “easily accessible form, using clear and plain language”. According to the European Data Protection Board: “A controller that offers a service in a country should also offer answers in the language that is understood by the data subjects in that country.” (European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 140)
Please respond to my request in {request_language} instead.`,
        'other-language::you-said-that::issue': `the company responded to your request in a different language.`,
        'other-language::you-said-that::meta': `You said that the company responded in {response_language} to your request in {request_language}. You said that you[user_does_not_understand_response_language> don’t] understand the company’s response in {response_language}.`,
        'other-language::complaint::persists': `The controller has answered my request in {response_language}, even though my request was in {request_language}.[user_does_not_understand_response_language> I cannot understand the controller’s response in {response_language}.] According to Art. 12(1) GDPR, they have to provide communication related to requests in “easily accessible form, using clear and plain language”. According to the European Data Protection Board: “A controller that offers a service in a country should also offer answers in the language that is understood by the data subjects in that country.” (European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 140)`,
        'other-language::complaint::resolved': `The controller had initially answered my request in {response_language}, even though my request was in {request_language}[user_does_not_understand_response_language> and I couldn’t understand the controller’s response in {response_language}]. This issue has since been resolved.`,

        'excessive::admonition': `[controller_refuses>You have refused to act on my request.][controller_wants_to_charge>You want to charge a fee for my request.] According to Art. 12(5) GDPR, you can only do that for manifestly unfounded or excessive requests[controller_gave_no_reasoning> and you bear the burden of demonstrating the manifestly unfounded or excessive character of my request. You have not done that].[controller_wants_to_charge> Alternatively, you could charge a fee based on Art. 15(3) GDPR for further copies that I have requested.]

I don’t believe that you can [controller_refuses>refuse to act on my request][controller_wants_to_charge>charge me for my request] in this case[controller_gave_no_reasoning> and you have not argued to the contrary]. [first_request>This is the first request I have ever sent to you. As such, it is not apparent to me how it could possibly be considered unfounded or excessive. You can also never charge a fee for the first copy, regardless of whether you consider the cost of producing it to be too high (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 22).][additional_copy_no_prior_request>I have never sent you a request before. As such, it is not apparent how I could be asking for an additional copy of my data. You can never charge a fee for the first copy, regardless of whether you consider the cost of producing it to be too high (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 22).][concerns_different_data>You claim that I am asking for an additional copy of my data. However, this would only apply if this request concerned the same data as my previous request. If the request instead concerns different data (e.g. different data types or a different timeframe), you have to consider it a new request and the right to a free copy applies again (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 28). I believe that to be the case here.][has:reasoning>{reasoning}]`,
        'excessive::you-said-that::issue': `the company [controller_refuses>refused to act on your request][controller_wants_to_charge>wants to charge a fee for your request].`,
        'excessive::you-said-that::meta': `[controller_gave_no_reasoning>You said that the company didn’t give a reason.][first_request>You said that this was your first request to the company.][additional_copy_no_prior_request>You said that the company claimed you were asking for an additional copy of your data, but this was in fact your first request to them.][concerns_different_data>You said that the company claimed you were asking for an additional copy of your data, but you believe you were asking for different data.][has:reasoning>You gave your own reasoning: “{reasoning}”]`,
        'excessive::complaint::persists': `[controller_refuses>The controller refused to act on my request.][controller_wants_to_charge>The controller wants to charge a fee for my request.] According to Art. 12(5) GDPR, they can only do that for manifestly unfounded or excessive requests[controller_gave_no_reasoning> and they bear the burden of demonstrating the manifestly unfounded or excessive character of my request. They have not done that].[controller_wants_to_charge> Alternatively, they could charge a fee based on Art. 15(3) GDPR for further copies that I have requested.]

I don’t believe that they can [controller_refuses>refuse to act on my request][controller_wants_to_charge>charge me for my request] in this case[controller_gave_no_reasoning> and they have not argued to the contrary]. [first_request>This is the first request I have ever sent to the controller. As such, it is not apparent to me how it could possibly be considered unfounded or excessive. The controller can also never charge a fee for the first copy, regardless of whether they consider the cost of producing it to be too high (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 22).][additional_copy_no_prior_request>I have never sent a request to the controller before. As such, it is not apparent how I could be asking for an additional copy of my data. The controller can never charge a fee for the first copy, regardless of whether they consider the cost of producing it to be too high (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 22).][concerns_different_data>The controller claims that I am asking for an additional copy of my data. However, this would only apply if this request concerned the same data as my previous request. If the request instead concerns different data (e.g. different data types or a different timeframe), you have to consider it a new request and the right to a free copy applies again (cf. European Data Protection Board, “Guidelines 01/2022 on data subject rights - Right of access”, Version 1.0, para. 28). I believe that to be the case here.][has:reasoning>{reasoning}]`,
        'excessive::complaint::resolved': `[controller_refuses>The controller had initially refused to act on my request.][controller_wants_to_charge>The controller had initially wanted to charge a fee for my request.] According to Art. 12(5) GDPR, they can only do that for manifestly unfounded or excessive requests.[controller_wants_to_charge> Alternatively, they could charge a fee based on Art. 15(3) GDPR for further copies that I have requested.] This was not the case here. This issue has since been resolved.`,

        'overdue::admonition': `You have not answered my request yet. According to Art. 12(3) GDPR, you have one month from the receipt of my request to answer it. I sent my request on {request_date}, which means that you have exceeded that period. According to Art. 12(3) GDPR, the period can be extended for an additional two months only if necessary and if you inform me of the extension and its reason. [no_information_about_extension>You have not done that.][has:reasoning>The reason you gave for the extension is not acceptable in my opinion: {reasoning}][more_than_three_months>
You have now exceeded even the extended three-month period.]`,
        'overdue::you-said-that::issue': `the company took too long to answer your request.`,
        'overdue::you-said-that::meta': `You sent your request on {request_date}. [no_information_about_extension>You said that the company didn’t inform you why they needed longer than one month to answer your request.][has:reasoning>You gave your own reasoning why you think the company’s justification of the extension was not appropriate: “{reasoning}”]`,
        'overdue::complaint::persists': `The controller took too long to answer my request. According to Art. 12(3) GDPR, they have one month from the receipt of my request to answer it. I sent my request on {request_date}. According to Art. 12(3) GDPR, the period can be extended for an additional two months only if necessary and if they inform me of the extension and its reason. [no_information_about_extension>The controller did not do that.][has:reasoning>The reason the controller gave for the extension is not acceptable in my opinion: {reasoning}]
I have still not received an answer to my request.`,
        'overdue::complaint::resolved': `The controller took too long to answer my request. According to Art. 12(3) GDPR, they had one month from the receipt of my request to answer it. I sent my request on {request_date}. According to Art. 12(3) GDPR, the period can be extended for an additional two months only if necessary and if they inform me of the extension and its reason. [no_information_about_extension>The controller did not do that.][has:reasoning>The reason the controller gave for the extension is not acceptable in my opinion: {reasoning}]
The controller has now answered my request but still violated the GDPR by exceeding the period.`,
    },
};

export const template = (lang: keyof typeof templates, template: keyof typeof templates.en) => {
    const res = templates[lang as 'en']?.[template];
    if (res) return res;
    return templates.en[template];
};
