newPRWelcomeComment: |
  Thank you for making your first PR on `website`! 💖
  
  We are glad about every contribution!

  Feel free to add yourself to our [`AUTHORS` file](https://github.com/datenanfragen/website/blob/master/AUTHORS) to appear as a contributor on our website(s)e, e.g. [datarequests.org/open-source](https://www.datarequests.org/open-source/#contributors)
