[build]
publish = "public"
command = "./deploy.sh"

[context.production.environment]
HUGO_VERSION = "0.74.3"
YARN_VERSION = "1.22.4"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"
YARN_VERSION = "1.22.4"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"
YARN_VERSION = "1.22.4"
