import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import glob from 'glob';
import { getDirname } from 'cross-dirname';

const dirname = getDirname();

const svas = glob
    .sync('*.json', { cwd: join(dirname, '..', 'static', 'db', 'sva'), absolute: true })
    .map((p) => readFileSync(p, 'utf8'))
    .map((f) => JSON.parse(f));

const svaNames = svas.reduce((acc, cur) => ({ ...acc, [cur.slug]: cur.name }), {
    __note: 'This file is automatically generated by scripts/collect-sva-names.ts',
} as Record<string, string>);

writeFileSync(join(dirname, '..', 'src', 'Utility', 'sva-names.json'), JSON.stringify(svaNames, null, 4));
